### ISSUE TITLE
Identify proper secure structure for the ECC codes both at codeword level and data set level (provide a code that secures the entire dataset)

### ISSUE THREAD

**Issue by dryajov** [codex-storage/codex-research#53]
- [x] Correction of random erasures
- [ ] Correction of adversarial erasures
- [ ] Inefficiency factor (how far is it from the ideal)
- [x] Identify encoding and decoding throughput
